function plotcolor(V,col)
    % plots a dense 3-dimensional trajectory V as a surface
    surface([V(:,1)';V(:,1)'],[V(:,2)';V(:,2)'],[V(:,3)';V(:,3)'],[col';col'],...
    'facecol','no',...
    'edgecol','interp',...
    'linew',2);
end